export const AUTHOR_LOGIN_REQUEST = "AUTHOR_LOGIN_REQUEST";
export const AUTHOR_LOGIN_SUCCESS = "AUTHOR_LOGIN_SUCCESS";
export const AUTHOR_LOGIN_FAIL = "AUTHOR_LOGIN_FAIL";
export const AUTHOR_LOGOUT = "AUTHOR_LOGOUT";


export const AUTHOR_REGISTER_REQUEST = "AUTHOR_REGISTER_REQUEST";
export const AUTHOR_REGISTER_SUCCESS = "AUTHOR_REGISTER_SUCCESS";
export const AUTHOR_REGISTER_FAIL = "AUTHOR_REGISTER_FAIL";


